stack_name:  stack-name-{{ env_name }}
image_name:  gitlab.ru:5050/app:{{ env_values.version }}
workdir:     /home/{{ ansible_user }}/dirnanme-{{ env_name }}

vault_path_secrets_v2:
  - path: secret-path/data/secret-key,token
    key: vault_token
    format: string
  - path: secret-path/data/secret-key,vats_gitlab_token.yaml
    key: vats

prod:
  version: 0.2.7
  env:
    EZCONFIG_ENVIRONMENT: prod
    # DEBUG__ENABLE_SQLALCHEMY_LOGS: "True"
    # DEBUG__EMAIL_DISABLED: "True"
